[build]
  publish = "build/web"
  command = "chmod +x install_flutter.sh && ./install_flutter.sh && flutter build web --release --web-renderer html"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
